Work around mysterious RTD failure:
```
writing output... [ 14%] meetings/community/2018-07-19

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupyterhub-team-compass/envs/609/lib/python3.10/site-packages/sphinx/cmd/build.py", line 281, in build_main
    app.build(args.force_all, args.filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupyterhub-team-compass/envs/609/lib/python3.10/site-packages/sphinx/application.py", line 347, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupyterhub-team-compass/envs/609/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 310, in build_update
    self.build(to_build,
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupyterhub-team-compass/envs/609/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 376, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupyterhub-team-compass/envs/609/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 571, in write
    self._write_serial(sorted(docnames))
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupyterhub-team-compass/envs/609/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 578, in _write_serial
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupyterhub-team-compass/envs/609/lib/python3.10/site-packages/sphinx/environment/__init__.py", line 591, in get_and_resolve_doctree
    self.apply_post_transforms(doctree, docname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupyterhub-team-compass/envs/609/lib/python3.10/site-packages/sphinx/environment/__init__.py", line 637, in apply_post_transforms
    transformer.apply_transforms()
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupyterhub-team-compass/envs/609/lib/python3.10/site-packages/sphinx/transforms/__init__.py", line 80, in apply_transforms
    super().apply_transforms()
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupyterhub-team-compass/envs/609/lib/python3.10/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupyterhub-team-compass/envs/609/lib/python3.10/site-packages/sphinx/transforms/post_transforms/__init__.py", line 35, in apply
    self.run(**kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupyterhub-team-compass/envs/609/lib/python3.10/site-packages/pydata_sphinx_theme/__init__.py", line 958, in run
    node.children[0] = nodes.Text(self.parse_url(uri))
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupyterhub-team-compass/envs/609/lib/python3.10/site-packages/pydata_sphinx_theme/__init__.py", line 998, in parse_url
    group_and_subgroups, parts, *_ = path.split("/-/")
ValueError: not enough values to unpack (expected at least 2, got 1)

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupyterhub-team-compass/envs/609/lib/python3.10/site-packages/pydata_sphinx_theme/__init__.py", line 998, in parse_url
    group_and_subgroups, parts, *_ = path.split("/-/")
ValueError: not enough values to unpack (expected at least 2, got 1)
The full traceback has been saved in /tmp/sphinx-err-luhb4tq5.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
which corresponds to
https://github.com/pydata/pydata-sphinx-theme/blob/8e8ed5088c56e3a26979ea106786b60af92d9269/src/pydata_sphinx_theme/__init__.py#L995-L998